### ISSUE TITLE
Update method returns null object

### ISSUE THREAD

**Issue by ReubenFrimpong** [thepinecode/policy#4]
Hi,
According to the docs the update method is supposed to be used like this `$Gate.allow('update',post)`. However this returns false always. Furthermore, the blog post linked also implements it differently `$gate.allow('update','post', post)` which also returns a null object. Could it be that something is not being done properly?

**Comment by iamgergo** [comment]
Hey,

The blog post and the package have a different code at the moment, so you should  not compare them directly.
But for the update fix, feel free to open a PR.

**Comment by ReubenFrimpong** [comment]
My bad. I forgot to add the `use UsesModelName;` and `protected $appends = ['model_name']; ` to my Eloquent model. Everything works fine.
Thanks for such a wonderful package. I'm considering a blog post for it.
