### ISSUE TITLE
PHP8-compatibility

### ISSUE THREAD

**Issue by ahoiroman** [thepinecode/policy#5]
Hi there,

I'd like to try this package, but I would need PHP8-support. Maybe something you could add?

Thanks :-)

**Comment by karlebh** [comment]
Hello, this package is a Javascript package and as such is compatible with PHP 8 except if you need something different.

**Comment by iamgergo** [comment]
Hey,

I added PHP 8 support in the `0.4.1` release.

Thanks!

**Comment by ahoiroman** [comment]
> Hello, this package is a Javascript package and as such is compatible with PHP 8 except if you need something different.

That's not correct ;-) It contains JS, but it is a composer PHP project.

> I added PHP 8 support in the 0.4.1 release.

Alright, thanks a lot :-)
